[Interface]
Address = 10.255.0.1/24
ListenPort = 51820
PrivateKey = uC495o35/WdNm61B5+ZklBvmlRjqSwaAYqQt4VbCa1Y=

# Add staff peers here
# [Peer]
# PublicKey = <<<STAFF_PUBLICKEY>>>
# AllowedIPs = 10.255.0.10/32
